version: '3.3'

services:
  db:
    networks:
      default:
    image: mongo:4.2.3
    volumes:
      - altszama-mongodb-volume:/data/db
    restart: always

  backend:
    networks:
      default:
      monitoring_default:
        aliases:
        - altszamabackend
    depends_on:
      - db
    image: "konkit/altszama-backend:${DOCKER_TAG:-latest-master}"
    restart: always
    environment:
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_PORT: $DATABASE_PORT
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
      JWT_SIGNING_KEY: $JWT_SIGNING_KEY
      ORIGIN_URL: $ORIGIN_URL
      VAPID_PUBLIC_KEY: $VAPID_PUBLIC_KEY
      VAPID_PRIVATE_KEY: $VAPID_PRIVATE_KEY
      VAPID_SUBJECT: $VAPID_SUBJECT
      SENTRY_URL: $SENTRY_URL
      spring_profiles_active: $spring_profiles_active

  frontend:
    networks:
      default:
    depends_on:
      - backend
    image: "konkit/altszama-frontend:${DOCKER_TAG:-latest-master}"
    restart: always

  frontend-angular:
    networks:
      default:
    depends_on:
      - backend
    image: "konkit/altszama-frontend:${DOCKER_TAG:-latest-master}-angular"
    restart: always

  reverse-proxy:
    networks:
      default:
    depends_on:
      - backend
      - frontend
    image: "konkit/altszama-reverse-proxy:${DOCKER_TAG:-latest-master}"
    restart: always
    ports:
      - "127.0.0.1:${TARGET_PORT}:80"
      - "127.0.0.1:${TARGET_PORT_NEW}:8001"

volumes:
  altszama-mongodb-volume:

networks:
  default:
  monitoring_default:
    external: true
