/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AllOrdersOrderDto { 
    id: string;
    restaurantName: string;
    orderCreatorUsername: string;
    orderDate: string;
    orderState: AllOrdersOrderDto.OrderStateEnum;
}
export namespace AllOrdersOrderDto {
    export type OrderStateEnum = 'CREATED' | 'ORDERING' | 'ORDERED' | 'DELIVERED' | 'REJECTED';
    export const OrderStateEnum = {
        Created: 'CREATED' as OrderStateEnum,
        Ordering: 'ORDERING' as OrderStateEnum,
        Ordered: 'ORDERED' as OrderStateEnum,
        Delivered: 'DELIVERED' as OrderStateEnum,
        Rejected: 'REJECTED' as OrderStateEnum
    };
}


