/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AllOrdersOrderDto} from './allOrdersOrderDto';


export interface AllOrdersResponse {
    allOrdersList: Array<AllOrdersOrderDto>;
}

