/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DishEntryDishData } from './dishEntryDishData';
import { SideDish } from './sideDish';

export interface DishEntryDto { 
    restaurantName: string;
    dish: DishEntryDishData;
    chosenSideDishes: Array<SideDish>;
    additionalComments: string;
    id: string;
}