/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SideDish} from './sideDish';
import {DishEntryDishData} from './dishEntryDishData';


export interface DishEntryDto {
    restaurantName: string;
    dish: DishEntryDishData;
    chosenSideDishes: Array<SideDish>;
    additionalComments: string;
    id: string;
}

