/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {DishDto} from './dishDto';


export interface EditDishResponse {
    dish: DishDto;
    categories: Array<string>;
}

