/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AuthUserInfo} from './authUserInfo';


export interface GoogleAuthSuccess {
    userInfo: AuthUserInfo;
}

