/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {EatingPersonEntry} from './eatingPersonEntry';


export interface GroupedOrderEntry {
    dishName: string;
    price: number;
    eatingPeopleCount: number;
    eatingPeopleEntries: Array<EatingPersonEntry>;
}

