/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ImportCredentials} from './importCredentials';
import {RestaurantInfo} from './restaurantInfo';


export interface IndexResponse {
    restaurants: Array<RestaurantInfo>;
    importCredentials: ImportCredentials;
}

