/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {OrderHistoryCreatedEntry} from './orderHistoryCreatedEntry';
import {OrderHistoryParticipatedEntry} from './orderHistoryParticipatedEntry';


/**
 * @type OrderHistoryEntry
 * @export
 */
export type OrderHistoryEntry = OrderHistoryCreatedEntry | OrderHistoryParticipatedEntry;

