/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderHistoryParticipatedEntry { 
    orderId: string;
    orderDate: string;
    orderCreator: string;
    restaurantName: string;
    orderEntryAmount: number;
    status: OrderHistoryParticipatedEntry.StatusEnum;
    kind: string;
}
export namespace OrderHistoryParticipatedEntry {
    export type StatusEnum = 'UNPAID' | 'CONFIRMED';
    export const StatusEnum = {
        Unpaid: 'UNPAID' as StatusEnum,
        Confirmed: 'CONFIRMED' as StatusEnum
    };
}


