/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryData } from './deliveryData';
import { GroupedOrderEntry } from './groupedOrderEntry';

export interface OrderViewInitialData { 
    orderState: OrderViewInitialData.OrderStateEnum;
    orderDeliveryData: DeliveryData;
    restaurantName: string;
    restaurantTelephone: string;
    groupedEntries: Array<GroupedOrderEntry>;
    allEatingPeopleCount: number;
    basePriceSum: number;
    totalPrice: number;
}
export namespace OrderViewInitialData {
    export type OrderStateEnum = 'CREATED' | 'ORDERING' | 'ORDERED' | 'DELIVERED' | 'REJECTED';
    export const OrderStateEnum = {
        CREATED: 'CREATED' as OrderStateEnum,
        ORDERING: 'ORDERING' as OrderStateEnum,
        ORDERED: 'ORDERED' as OrderStateEnum,
        DELIVERED: 'DELIVERED' as OrderStateEnum,
        REJECTED: 'REJECTED' as OrderStateEnum
    };
}