/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderHistoryCreatedEntry { 
    orderId: string;
    orderDate: string;
    orderCreator: string;
    restaurantName: string;
    confirmedPaymentsTotalAmount: number;
    totalAmount: number;
    kind: string;
}

