/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {DishEntryDto} from './dishEntryDto';


export interface OrderEntryDto {
    id: string;
    orderId: string;
    orderState: OrderEntryDto.OrderStateEnum;
    dishEntries: Array<DishEntryDto>;
    paymentStatus: OrderEntryDto.PaymentStatusEnum;
    created: string;
}
export namespace OrderEntryDto {
    export type OrderStateEnum = 'CREATED' | 'ORDERING' | 'ORDERED' | 'DELIVERED' | 'REJECTED';
    export const OrderStateEnum = {
        Created: 'CREATED' as OrderStateEnum,
        Ordering: 'ORDERING' as OrderStateEnum,
        Ordered: 'ORDERED' as OrderStateEnum,
        Delivered: 'DELIVERED' as OrderStateEnum,
        Rejected: 'REJECTED' as OrderStateEnum
    };
    export type PaymentStatusEnum = 'UNPAID' | 'CONFIRMED';
    export const PaymentStatusEnum = {
        Unpaid: 'UNPAID' as PaymentStatusEnum,
        Confirmed: 'CONFIRMED' as PaymentStatusEnum
    };
}


