/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderHistoryEntry } from './orderHistoryEntry';

export interface OrderHistoryParticipatedEntry extends OrderHistoryEntry { 
    orderEntryAmount: number;
    status: OrderHistoryParticipatedEntry.StatusEnum;
}
export namespace OrderHistoryParticipatedEntry {
    export type StatusEnum = 'UNPAID' | 'CONFIRMED';
    export const StatusEnum = {
        UNPAID: 'UNPAID' as StatusEnum,
        CONFIRMED: 'CONFIRMED' as StatusEnum
    };
}