/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {ParticipantsDishEntry} from './participantsDishEntry';


export interface ParticipantsOrderEntry {
    id: string;
    userId: string;
    username: string;
    dishEntries: Array<ParticipantsDishEntry>;
    finalPrice: number;
    paymentStatus: ParticipantsOrderEntry.PaymentStatusEnum;
}
export namespace ParticipantsOrderEntry {
    export type PaymentStatusEnum = 'UNPAID' | 'CONFIRMED';
    export const PaymentStatusEnum = {
        Unpaid: 'UNPAID' as PaymentStatusEnum,
        Confirmed: 'CONFIRMED' as PaymentStatusEnum
    };
}


