/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentData { 
    paymentByCash: boolean;
    paymentByBankTransfer: boolean;
    bankTransferNumber: string;
    paymentByBlik: boolean;
    blikPhoneNumber: string;
}

