/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RestaurantInfo { 
    id: string;
    name: string;
    lastCrawled?: string;
    lastEdited?: string;
    dishCount: number;
}

