/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {RestaurantDto} from './restaurantDto';
import {DishDto} from './dishDto';


export interface ShowRestaurantResponse {
    restaurant: RestaurantDto;
    dishes: Array<DishDto>;
    dishesByCategory: { [key: string]: Array<DishDto>; };
}

