/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DishDto } from './dishDto';
import { ParticipantsOrderEntry } from './participantsOrderEntry';
import { ShowOrderDto } from './showOrderDto';
import { SideDish } from './sideDish';

export interface ShowOrderResponse { 
    order: ShowOrderDto;
    orderEntries: Array<ParticipantsOrderEntry>;
    currentUserId: string;
    allDishesInRestaurant: Array<DishDto>;
    allDishesByCategory: { [key: string]: Array<DishDto>; };
    dishIdToSideDishesMap: { [key: string]: Array<SideDish>; };
    baseOrderPrice: number;
    totalOrderPrice: number;
}