/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PaymentData} from './paymentData';
import {DeliveryData} from './deliveryData';


export interface ShowOrderDto {
    id: string;
    restaurantId: string;
    restaurantName: string;
    restaurantUrl: string;
    orderCreatorId: string;
    orderCreatorUsername: string;
    orderDate: string;
    timeOfOrder?: string;
    timeOfDelivery?: string;
    orderState: ShowOrderDto.OrderStateEnum;
    deliveryData: DeliveryData;
    paymentData: PaymentData;
}
export namespace ShowOrderDto {
    export type OrderStateEnum = 'CREATED' | 'ORDERING' | 'ORDERED' | 'DELIVERED' | 'REJECTED';
    export const OrderStateEnum = {
        Created: 'CREATED' as OrderStateEnum,
        Ordering: 'ORDERING' as OrderStateEnum,
        Ordered: 'ORDERED' as OrderStateEnum,
        Delivered: 'DELIVERED' as OrderStateEnum,
        Rejected: 'REJECTED' as OrderStateEnum
    };
}


