/**
 * Restaurant Import API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SideDishData { 
    isNew?: boolean;
    newSideDishName?: string;
    newSideDishPrice?: number;
    id?: string;
}

