/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {LocalTime} from './localTime';


export interface TodayOrderDto {
    id: string;
    restaurantId: string;
    restaurantName: string;
    orderCreatorId: string;
    orderCreatorUsername: string;
    orderDate: string;
    timeOfOrder?: string;
    timeOfDelivery?: LocalTime;
    orderState: TodayOrderDto.OrderStateEnum;
    decreaseInPercent: number;
    deliveryCostPerEverybody: number;
    deliveryCostPerDish: number;
    paymentByCash: boolean;
    paymentByBankTransfer: boolean;
    bankTransferNumber: string;
}
export namespace TodayOrderDto {
    export type OrderStateEnum = 'CREATED' | 'ORDERING' | 'ORDERED' | 'DELIVERED' | 'REJECTED';
    export const OrderStateEnum = {
        Created: 'CREATED' as OrderStateEnum,
        Ordering: 'ORDERING' as OrderStateEnum,
        Ordered: 'ORDERED' as OrderStateEnum,
        Delivered: 'DELIVERED' as OrderStateEnum,
        Rejected: 'REJECTED' as OrderStateEnum
    };
}


