/**
 * Restaurant Import API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {TodayOrderDto} from './todayOrderDto';
import {OrderEntryDto} from './orderEntryDto';


export interface TodayOrdersResponse {
    ordersList: Array<TodayOrderDto>;
    currentOrderEntries: Array<OrderEntryDto>;
}

