export * from './authController.service';
import {AuthControllerService} from './authController.service';
import {BalanceControllerService} from './balanceController.service';
import {DishControllerService} from './dishController.service';
import {NotificationControllerService} from './notificationController.service';
import {OrderControllerService} from './orderController.service';
import {OrderEntryControllerService} from './orderEntryController.service';
import {RestaurantControllerService} from './restaurantController.service';
import {TestAuthControllerService} from './testAuthController.service';
import {TestEnvironmentControllerService} from './testEnvironmentController.service';

export * from './balanceController.service';
export * from './dishController.service';
export * from './notificationController.service';
export * from './orderController.service';
export * from './orderEntryController.service';
export * from './restaurantController.service';
export * from './testAuthController.service';
export * from './testEnvironmentController.service';
export const APIS = [AuthControllerService, BalanceControllerService, DishControllerService, NotificationControllerService, OrderControllerService, OrderEntryControllerService, RestaurantControllerService, TestAuthControllerService, TestEnvironmentControllerService];
