export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './balanceController.service';
import { BalanceControllerService } from './balanceController.service';
export * from './dishController.service';
import { DishControllerService } from './dishController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './orderEntryController.service';
import { OrderEntryControllerService } from './orderEntryController.service';
export * from './restaurantController.service';
import { RestaurantControllerService } from './restaurantController.service';
export * from './testAuthController.service';
import { TestAuthControllerService } from './testAuthController.service';
export * from './testEnvironmentController.service';
import { TestEnvironmentControllerService } from './testEnvironmentController.service';
export const APIS = [AuthControllerService, BalanceControllerService, DishControllerService, NotificationControllerService, OrderControllerService, OrderEntryControllerService, RestaurantControllerService, TestAuthControllerService, TestEnvironmentControllerService];
