/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateDishResponse } from '../model/createDishResponse';
import { DishCreateRequest } from '../model/dishCreateRequest';
import { DishUpdateRequest } from '../model/dishUpdateRequest';
import { EditDishResponse } from '../model/editDishResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DishControllerService {

    protected basePath = 'http://localhost:8080/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param restaurantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createDish(restaurantId: string, observe?: 'body', reportProgress?: boolean): Observable<CreateDishResponse>;
    public createDish(restaurantId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CreateDishResponse>>;
    public createDish(restaurantId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CreateDishResponse>>;
    public createDish(restaurantId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling createDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CreateDishResponse>('get',`${this.basePath}/api/restaurants/${encodeURIComponent(String(restaurantId))}/dishes/create.json`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param dishId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDish(dishId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public deleteDish(dishId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public deleteDish(dishId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public deleteDish(dishId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dishId === null || dishId === undefined) {
            throw new Error('Required parameter dishId was null or undefined when calling deleteDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('delete',`${this.basePath}/api/dishes/${encodeURIComponent(String(dishId))}/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param dishId 
     * @param sideDishId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSideDish(dishId: string, sideDishId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public deleteSideDish(dishId: string, sideDishId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public deleteSideDish(dishId: string, sideDishId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public deleteSideDish(dishId: string, sideDishId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dishId === null || dishId === undefined) {
            throw new Error('Required parameter dishId was null or undefined when calling deleteSideDish.');
        }

        if (sideDishId === null || sideDishId === undefined) {
            throw new Error('Required parameter sideDishId was null or undefined when calling deleteSideDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('delete',`${this.basePath}/api/dishes/${encodeURIComponent(String(dishId))}/side_dishes/${encodeURIComponent(String(sideDishId))}/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param restaurantId 
     * @param dishId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public editDish(restaurantId: string, dishId: string, observe?: 'body', reportProgress?: boolean): Observable<EditDishResponse>;
    public editDish(restaurantId: string, dishId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<EditDishResponse>>;
    public editDish(restaurantId: string, dishId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<EditDishResponse>>;
    public editDish(restaurantId: string, dishId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling editDish.');
        }

        if (dishId === null || dishId === undefined) {
            throw new Error('Required parameter dishId was null or undefined when calling editDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<EditDishResponse>('get',`${this.basePath}/api/restaurants/${encodeURIComponent(String(restaurantId))}/dishes/${encodeURIComponent(String(dishId))}/edit.json`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param restaurantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveDish(body: DishCreateRequest, restaurantId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public saveDish(body: DishCreateRequest, restaurantId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public saveDish(body: DishCreateRequest, restaurantId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public saveDish(body: DishCreateRequest, restaurantId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling saveDish.');
        }

        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling saveDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('post',`${this.basePath}/api/restaurants/${encodeURIComponent(String(restaurantId))}/dishes/save`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param restaurantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDish(body: DishUpdateRequest, restaurantId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public updateDish(body: DishUpdateRequest, restaurantId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public updateDish(body: DishUpdateRequest, restaurantId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public updateDish(body: DishUpdateRequest, restaurantId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateDish.');
        }

        if (restaurantId === null || restaurantId === undefined) {
            throw new Error('Required parameter restaurantId was null or undefined when calling updateDish.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('put',`${this.basePath}/api/restaurants/${encodeURIComponent(String(restaurantId))}/dishes/update`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
