/**
 * Restaurant Import API
 * To use the API please use the Import API Key specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { OrderEntrySaveRequest } from '../model/orderEntrySaveRequest';
import { OrderEntryUpdateRequest } from '../model/orderEntryUpdateRequest';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class OrderEntryControllerService {

    protected basePath = 'http://localhost:8080/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param orderEntryId 
     * @param dishEntryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public delete1(orderEntryId: string, dishEntryId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public delete1(orderEntryId: string, dishEntryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public delete1(orderEntryId: string, dishEntryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public delete1(orderEntryId: string, dishEntryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderEntryId === null || orderEntryId === undefined) {
            throw new Error('Required parameter orderEntryId was null or undefined when calling delete1.');
        }

        if (dishEntryId === null || dishEntryId === undefined) {
            throw new Error('Required parameter dishEntryId was null or undefined when calling delete1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('delete',`${this.basePath}/api/order_entries/${encodeURIComponent(String(orderEntryId))}/dish_entry/${encodeURIComponent(String(dishEntryId))}/delete`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param orderEntryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public revertToUnpaid(orderEntryId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public revertToUnpaid(orderEntryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public revertToUnpaid(orderEntryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public revertToUnpaid(orderEntryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderEntryId === null || orderEntryId === undefined) {
            throw new Error('Required parameter orderEntryId was null or undefined when calling revertToUnpaid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('put',`${this.basePath}/api/order_entries/${encodeURIComponent(String(orderEntryId))}/revert_to_unpaid`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public save1(body: OrderEntrySaveRequest, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public save1(body: OrderEntrySaveRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public save1(body: OrderEntrySaveRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public save1(body: OrderEntrySaveRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling save1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('post',`${this.basePath}/api/order_entries/save`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param orderEntryId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setAsConfirmedAsPaid(orderEntryId: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public setAsConfirmedAsPaid(orderEntryId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public setAsConfirmedAsPaid(orderEntryId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public setAsConfirmedAsPaid(orderEntryId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (orderEntryId === null || orderEntryId === undefined) {
            throw new Error('Required parameter orderEntryId was null or undefined when calling setAsConfirmedAsPaid.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('put',`${this.basePath}/api/order_entries/${encodeURIComponent(String(orderEntryId))}/confirm_as_paid`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public update1(body: OrderEntryUpdateRequest, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public update1(body: OrderEntryUpdateRequest, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public update1(body: OrderEntryUpdateRequest, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public update1(body: OrderEntryUpdateRequest, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling update1.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<string>('put',`${this.basePath}/api/order_entries/update`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
