// tslint:disable
/**
 * Restaurant Import API
 * To use the API pleaes use Basic Authentication with credentials specified on \"Restaurants\" page
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
